#!/usr/bin/env php

<?php 

require_once __DIR__ . '/vendor/autoload.php'; 

use Symfony\Component\Console\Application; 
use Console\NewsCommand;

/**
* Author: Chidume Nnamdi <kurtwanger40@gmail.com>
*/

$app = new Application('Console App', 'v1.0.0');

$app -> add(new NewsCommand());
$app->setDefaultCommand('news', true); // Single command application
$app -> run();
